spring.application.name=jinutechcompany

spring.data.mongodb.database=employeeonbording-db
spring.data.mongodb.uri=mongodb+srv://jinumistika03:JINU_mistika03@cluster0.srwzvle.mongodb.net/?appName=Cluster0

